if has('gui_running')

    colorscheme solarized
    "colorscheme Tomorrow-Night

    set cursorline
    set number

    " airline / powerline
    set guifont=Menlo\ for\ Powerline
    set laststatus=2 " make sure vim-airline shows up
    let g:airline_enable_syntastic=1
    let g:airline_theme='solarized2'
    let g:airline_powerline_fonts=1

    " Control-Shift-PageUp drags the active tab page to the left (wraps around)
    imap <silent> <C-S-PageUp> <C-o>:call <Sid>DragLeft()<Cr>
    nmap <silent> <C-S-PageUp> :call <Sid>DragLeft()<Cr>

    function! s:DragLeft()
        let n = tabpagenr()
        execute 'tabmove' (n == 1 ? '' : n - 2)
        let &showtabline = &showtabline
    endfunction

    " Control-Shift-PageDown drags the active tab page to the right (wraps around)
    imap <silent> <C-S-PageDown> <C-o>:call <Sid>DragRight()<Cr>
    nmap <silent> <C-S-PageDown> :call <Sid>DragRight()<Cr>

    function! s:DragRight()
        let n = tabpagenr()
        execute 'tabmove' (n == tabpagenr('$') ? 0 : n)
        let &showtabline = &showtabline
    endfunction
endif

if has('gui_macvim')
    " no toolbar
    set guioptions=-t

    " transparency (use experimental renderer)
    set transparency=5

    " set Command-T to command-t
    macmenu &File.New\ Tab key=<nop>
    map <D-t> :CommandT<CR>
endif
