if has('gui_running')

    colorscheme solarized

	set cursorline
	set number

	" Control-Shift-PageUp drags the active tab page to the left (wraps around)
	imap <silent> <C-S-PageUp> <C-o>:call <Sid>DragLeft()<Cr>
	nmap <silent> <C-S-PageUp> :call <Sid>DragLeft()<Cr>

	function! s:DragLeft()
		let n = tabpagenr()
		execute 'tabmove' (n == 1 ? '' : n - 2)
		let &showtabline = &showtabline
	endfunction

	" Control-Shift-PageDown drags the active tab page to the right (wraps
	" around
	imap <silent> <C-S-PageDown> <C-o>:call <Sid>DragRight()<Cr>
	nmap <silent> <C-S-PageDown> :call <Sid>DragRight()<Cr>

	function! s:DragRight()
		let n = tabpagenr()
		execute 'tabmove' (n == tabpagenr('$') ? 0 : n)
		let &showtabline = &showtabline
	endfunction
endif

if has('gui_macvim')
	" no toolbar
	set guioptions=-t
	
	" transparency (use experimental renderer)
	set transparency=10

	" set Command-T to command-t
	macmenu &File.New\ Tab key=<nop>
	map <D-t> :CommandT<CR>
endif