# Path to your oh-my-zsh configuration.
ZSH=$HOME/dotfiles/zsh/oh-my-zsh
ZSH_CUSTOM=$HOME/dotfiles/zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="eff"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git osx)

source $ZSH/oh-my-zsh.sh

# project hotkeys
alias cdp="cd ~/Projects"
alias cds="cd ~/Projects/stumptown-v2"

# ALIAS
alias vag="vagrant"
alias glog="git log --graph --full-history --all --color --pretty=format:'%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s'"
alias glogg="git --no-pager log --graph --full-history --all --color --pretty=format:'%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s'"

# FUNCTIONS
hr(){printf '=%.0s' $(seq $COLUMNS)} # horizontal rule
__git_files () { _wanted files expl 'local files' _files } # speed up git autocomplete

# syntax-highlighting `less` (requires source-highlight)
export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"

# PATH

# homebrew
PATH="/usr/local/bin:${PATH}"

# postgres
PATH="/Library/PostgreSQL/9.1/bin:${PATH}"

# python
PATH="/usr/local/share/python:${PATH}"

# node
PATH="/usr/local/share/npm/bin:${PATH}"

export PATH
